---
title: "PA1_template"
author: "Ourives"
date: "Sunday, October 19, 2014"
output: html_document
---
```{r}
library(ggplot2)
setwd("C:\\Users\\Família\\Documents\\Ciência de Dados\\05 - Reproducible Research\\Peer Assessment 1\\")
base <- read.csv("activity.csv",header = T)
base$date <- as.character(base$date)
base$date <- as.Date(base$date, format="%Y-%m-%d")
baseNA <- is.na(base$steps)
baseClean <- base[!baseNA,]
```

```{r}
#Hist of the Sum
sum <- tapply(baseClean$steps, baseClean$date, sum)
hist(sum, main ="Histogram of Total Number of Steps", xlab = "Total of steps")
```

```{r}
#Mean
tapply(baseClean$steps, baseClean$date, mean)
```

```{r}
#Median
tapply(baseClean$steps, baseClean$date, median)
```

```{r}
#TS plot
avg <- tapply(baseClean$steps, baseClean$interval, mean)
avg_names <- names(avg)
plot(avg_names, avg, type = "l", main = "Average Number of Steps by interval of 5 minutes", xlab = "Interval", ylab = "Average")
```

```{r}
maximo <- avg_names[(avg==max(avg))]

##The interval who have the maximum number of steps is `r maximo`.
```

The interval who have the maximum number of steps is `r maximo`.


```{r}
countNA <- sum(is.na(base$steps))
```

The total number of NAs is `r countNA`

It will be use the mean of steps to fill the NA with 0 (zero).

```{r}
base$steps[is.na(base$steps)] <- 0
```

```{r}
#Hist of the Sum
sum <- tapply(base$steps, base$date, sum)
hist(sum, main = "Average Number of Steps by interval of 5 minutes", sub="With NA = 0", xlab = "Total of steps", ylab = "Average")
```

```{r}
#Mean
tapply(base$steps, base$date, mean)
```

```{r}
#Median
tapply(base$steps, base$date, median)
```

Comparing the two histograms, we realized that there was no great difference in the values, only the concentration of 0 in the histogram was evidenced.

```{r}
base$steps[is.na(base$steps)] <- 0

base$weekday <- weekdays(base$date)
base$w2 = "weekday"

base$w2[(weekdays(base$date) %in% c('sábado','domingo'))] <- "weekend"
base$w2 <- as.factor(base$w2)
```

```{r}
base_w2 <- aggregate( steps~w2+interval, base, mean )
qplot(interval,steps,data=base_w2,geom="line", facets = .~w2, xlab ="Interval" , ylab ="Steps") + facet_wrap(~w2,nrow = 2, ncol = 1)
```